server:
  port: 8080

spring:
  h2:
    console:
      enabled: true
      settings:
        web-allow-others: true
  #  datasource:
  #    url: jdbc:postgresql://postgresqldb:5432/HyperCore?serverTimezone=UTC
  #    username: postgres
  #    password: bestuser
  #    driver-class-name: org.postgresql.Driver

      url: jdbc:h2:file:/axalit_images/hypercore/db
      driver-class-name: org.h2.Driver
      username: sa
      password: password

  jpa:
    show-sql: true
    hibernate:
      ddl-auto: create
    database-platform: org.hibernate.dialect.H2Dialect
    defer-datasource-initialization: true

jwt:
  secret:
    access: qBTmv4oXFFR2GwjexDJ4t6fsIUIUhhXqlktXjXdkcyygs8nPVEwMfo29VDRRepYDVV5IkIxBMzr7OEHXEHd37w==
    refresh: zL1HB3Pch05Avfynovxrf/kpF9O2m4NCWKJUjEp27s9J2jEG3ifiKCGylaZ8fDeoONSTJP/wAzKawB8F9rOMNg==

variables:
  server-adress: localhost
